const recipes = [
  {
    id: '#1',
    name: 'Protein-Packed Greek Yogurt Parfait with Granola and Berries',
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: ['200g 0% fat Greek yogurt', '30g vanilla whey protein powder', '20g low-calorie granola', '100g mixed berries (strawberries, blueberries)', '5g chia seeds'],
    recipe: '1. Mix Greek yogurt with protein powder until smooth.\n2. In a bowl or jar, layer yogurt mixture, granola, and berries.\n3. Sprinkle chia seeds on top for added fiber and omega-3s.\n4. Serve immediately or chill for later.',
    macros: { protein: 48, carbs: 39, fats: 5 },
    calories: '395 kcal',
    insights: 'High in calcium, vitamin C, vitamin K, and antioxidants from berries. Perfect for a quick, nutrient-dense breakfast.',
    tags: ['high-protein', 'vegetarian', 'quick']
  },
  {
    id: '#2',
    name: 'Anabolic Cinnamon Roll Oatmeal',
    prepTime: '5 min',
    cookTime: '5 min',
    ingredients: ['50g rolled oats', '30g vanilla whey protein powder', '150ml unsweetened almond milk', '5g cinnamon', '10g sugar-free maple syrup', '100g sliced apple'],
    recipe: '1. Cook oats with almond milk in a microwave or stovetop until thick (2–3 min).\n2. Stir in protein powder, cinnamon, and syrup until smooth.\n3. Top with sliced apple for crunch and natural sweetness.',
    macros: { protein: 31, carbs: 56, fats: 5 },
    calories: '400 kcal',
    insights: 'Rich in fiber, vitamin C, and manganese. A cozy, high-protein breakfast with a cinnamon roll flavor.',
    tags: ['high-protein', 'vegetarian', 'fiber-rich']
  },
  {
    id: '#3',
    name: 'Egg White Veggie Scramble on Toast',
    prepTime: '10 min',
    cookTime: '10 min',
    ingredients: ['240g egg whites', '100g spinach', '50g cherry tomatoes, halved', '50g mushrooms, sliced', '2 slices whole-grain bread', '5g nutritional yeast'],
    recipe: '1. Sauté spinach, tomatoes, and mushrooms in a nonstick pan with cooking spray.\n2. Add egg whites and cook until set, stirring occasionally.\n3. Toast bread, then top with scramble and sprinkle with nutritional yeast for a cheesy flavor.',
    macros: { protein: 39, carbs: 40, fats: 2 },
    calories: '345 kcal',
    insights: 'High in vitamins A, C, K, folate, and B vitamins. A savory, protein-rich start to the day.',
    tags: ['high-protein', 'vegetarian', 'low-fat']
  },
  {
    id: '#4',
    name: 'Protein Pancake Stack with Peanut Butter Drizzle',
    prepTime: '5 min',
    cookTime: '10 min',
    ingredients: ['30g vanilla whey protein powder', '40g oat flour', '120g egg whites', '5g baking powder', '10g powdered peanut butter (mixed with water)', '10g sugar-free syrup'],
    recipe: '1. Blend protein powder, oat flour, egg whites, and baking powder with a splash of water.\n2. Cook batter in a nonstick pan over medium heat to form 3–4 small pancakes (2–3 min per side).\n3. Mix powdered peanut butter with water to make a drizzle, then top pancakes with drizzle and syrup.',
    macros: { protein: 45, carbs: 37, fats: 5 },
    calories: '380 kcal',
    insights: 'Good source of fiber, magnesium, and phosphorus from oats. A sweet, high-protein breakfast.',
    tags: ['high-protein', 'vegetarian', 'low-fat']
  },
  {
    id: '#5',
    name: 'Smoked Salmon and Cottage Cheese Bagel',
    prepTime: '5 min',
    cookTime: '2 min',
    ingredients: ['1 whole-grain mini bagel', '100g low-fat cottage cheese', '50g smoked salmon', '50g cucumber, sliced', '10g fresh dill'],
    recipe: '1. Toast the bagel lightly.\n2. Spread cottage cheese on both halves, then layer with smoked salmon and cucumber slices.\n3. Garnish with fresh dill for flavor.',
    macros: { protein: 27, carbs: 28, fats: 5 },
    calories: '270 kcal',
    insights: 'High in omega-3s, vitamin D, and calcium. A light, protein-packed breakfast with savory flavors.',
    tags: ['high-protein', 'low-calorie', 'omega-3']
  },
  {
    id: '#6',
    name: 'Chocolate Protein Yogurt Bowl',
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: ['200g 0% fat Greek yogurt', '30g chocolate whey protein powder', '20g low-calorie granola', '10g cocoa nibs', '50g raspberries'],
    recipe: '1. Mix yogurt with protein powder until smooth.\n2. Top with granola, cocoa nibs, and raspberries.\n3. Serve chilled for a refreshing breakfast.',
    macros: { protein: 48, carbs: 34, fats: 8 },
    calories: '405 kcal',
    insights: 'Rich in vitamin C, antioxidants, and calcium. A decadent yet healthy breakfast option.',
    tags: ['high-protein', 'vegetarian', 'antioxidant-rich']
  },
  {
    id: '#7',
    name: 'Turkey Bacon and Egg White Muffin',
    prepTime: '5 min',
    cookTime: '10 min',
    ingredients: ['240g egg whites', '50g turkey bacon, cooked', '50g spinach', '1 whole-grain English muffin', '10g low-fat cheese'],
    recipe: '1. Cook egg whites and spinach in a nonstick pan until set.\n2. Toast English muffin, then layer with turkey bacon, egg white mixture, and cheese.\n3. Serve warm or wrap for an on-the-go meal.',
    macros: { protein: 44, carbs: 29, fats: 9 },
    calories: '390 kcal',
    insights: 'High in vitamin K, calcium, and phosphorus. A portable, protein-rich breakfast.',
    tags: ['high-protein', 'portable']
  },
  {
    id: '#8',
    name: 'Berry Protein Smoothie Bowl',
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: ['30g vanilla whey protein powder', '150g frozen mixed berries', '100ml unsweetened almond milk', '20g low-calorie granola', '10g chia seeds'],
    recipe: '1. Blend protein powder, berries, and almond milk until thick.\n2. Pour into a bowl and top with granola and chia seeds.\n3. Serve immediately with a spoon.',
    macros: { protein: 29, carbs: 38, fats: 7 },
    calories: '335 kcal',
    insights: 'High in vitamin C, fiber, and omega-3s from chia seeds. A vibrant, refreshing breakfast.',
    tags: ['high-protein', 'vegetarian', 'low-calorie']
  },
  {
    id: '#9',
    name: 'Anabolic Breakfast Burrito',
    prepTime: '10 min',
    cookTime: '10 min',
    ingredients: ['240g egg whites', '100g ground turkey', '50g bell peppers, diced', '1 low-carb tortilla', '15g low-fat salsa'],
    recipe: '1. Cook ground turkey and bell peppers in a nonstick pan.\n2. Add egg whites and scramble until cooked.\n3. Warm tortilla, then fill with egg mixture and top with salsa. Roll up and serve.',
    macros: { protein: 50, carbs: 16, fats: 8 },
    calories: '350 kcal',
    insights: 'High in vitamin C, B6, and protein. A filling, low-carb breakfast option.',
    tags: ['high-protein', 'low-carb']
  },
  {
    id: '#10',
    name: 'Pumpkin Spice Protein Oatmeal',
    prepTime: '5 min',
    cookTime: '5 min',
    ingredients: ['50g rolled oats', '30g vanilla whey protein powder', '100g pumpkin puree', '5g pumpkin pie spice', '10g sugar-free syrup', '150ml unsweetened almond milk'],
    recipe: '1. Cook oats with almond milk and pumpkin puree in a microwave or stovetop.\n2. Stir in protein powder, pumpkin spice, and syrup.\n3. Serve warm with a sprinkle of extra spice if desired.',
    macros: { protein: 32, carbs: 52, fats: 5 },
    calories: '390 kcal',
    insights: 'High in vitamin A, fiber, and magnesium. A cozy, fall-inspired breakfast.',
    tags: ['high-protein', 'vegetarian', 'fiber-rich']
  },
  {
    id: '#11',
    name: 'Cottage Cheese and Fruit Toast',
    prepTime: '5 min',
    cookTime: '2 min',
    ingredients: ['2 slices whole-grain bread', '150g low-fat cottage cheese', '100g sliced strawberries', '5g chia seeds'],
    recipe: '1. Toast bread until golden.\n2. Spread cottage cheese evenly over toast, then top with strawberries and chia seeds.\n3. Serve immediately.',
    macros: { protein: 28, carbs: 44, fats: 7 },
    calories: '337 kcal',
    insights: 'High in calcium, vitamin C, and fiber. A quick, balanced breakfast.',
    tags: ['high-protein', 'vegetarian', 'quick']
  },
  {
    id: '#12',
    name: 'Protein French Toast Sticks',
    prepTime: '5 min',
    cookTime: '10 min',
    ingredients: ['2 slices whole-grain bread, cut into sticks', '180g egg whites', '15g vanilla whey protein powder', '5g cinnamon', '15g sugar-free syrup'],
    recipe: '1. Mix egg whites, protein powder, and cinnamon in a bowl.\n2. Dip bread sticks in mixture, then cook in a nonstick pan until golden (2–3 min per side).\n3. Serve with syrup for dipping.',
    macros: { protein: 39, carbs: 37, fats: 2 },
    calories: '340 kcal',
    insights: 'Good source of fiber and B vitamins from whole-grain bread. A fun, protein-packed breakfast.',
    tags: ['high-protein', 'vegetarian', 'low-fat']
  },
  {
    id: '#13',
    name: 'Savory Quinoa Protein Bowl',
    prepTime: '10 min',
    cookTime: '15 min',
    ingredients: ['50g cooked quinoa', '240g egg whites', '50g kale', '50g cherry tomatoes', '10g nutritional yeast'],
    recipe: '1. Cook quinoa according to package instructions.\n2. Sauté kale and tomatoes in a nonstick pan, then add egg whites and cook until set.\n3. Mix with quinoa, sprinkle with nutritional yeast, and serve warm.',
    macros: { protein: 36, carbs: 34, fats: 2 },
    calories: '315 kcal',
    insights: 'High in vitamins A, C, K, and B vitamins. A hearty, savory breakfast bowl.',
    tags: ['high-protein', 'vegetarian', 'low-fat']
  },
  {
    id: '#14',
    name: 'Apple Pie Yogurt Parfait',
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: ['200g 0% fat Greek yogurt', '30g vanilla whey protein powder', '20g low-calorie granola', '100g diced apple', '5g cinnamon'],
    recipe: '1. Mix yogurt with protein powder and cinnamon.\n2. Layer yogurt, granola, and diced apple in a bowl or jar.\n3. Serve chilled or at room temperature.',
    macros: { protein: 46, carbs: 42, fats: 3 },
    calories: '385 kcal',
    insights: 'High in calcium, vitamin C, and fiber. A flavorful apple pie-inspired breakfast.',
    tags: ['high-protein', 'vegetarian', 'quick']
  },
  {
    id: '#15',
    name: 'Turkey Sausage and Egg White Wrap',
    prepTime: '10 min',
    cookTime: '10 min',
    ingredients: ['1 low-carb tortilla', '100g lean turkey sausage, cooked', '180g egg whites', '50g spinach', '10g low-fat salsa'],
    recipe: '1. Cook turkey sausage and spinach in a nonstick pan.\n2. Add egg whites and scramble until cooked.\n3. Warm tortilla, fill with mixture, top with salsa, and roll up.',
    macros: { protein: 41, carbs: 17, fats: 9 },
    calories: '320 kcal',
    insights: 'High in vitamin K, protein, and phosphorus. A low-carb, protein-packed wrap.',
    tags: ['high-protein', 'low-carb']
  },
  {
    id: '#16',
    name: 'Chocolate Banana Protein Waffles',
    prepTime: '5 min',
    cookTime: '10 min',
    ingredients: ['30g chocolate whey protein powder', '40g oat flour', '100g mashed banana', '120g egg whites', '5g baking powder', '10g sugar-free syrup'],
    recipe: '1. Blend all ingredients (except syrup) into a batter.\n2. Cook in a preheated waffle maker until golden (4–5 min).\n3. Serve with syrup drizzled on top.',
    macros: { protein: 43, carbs: 56, fats: 4 },
    calories: '430 kcal',
    insights: 'High in potassium, fiber, and vitamin B6 from banana. A sweet, protein-rich breakfast.',
    tags: ['high-protein', 'vegetarian']
  },
  {
    id: '#17',
    name: 'Spinach and Feta Egg White Muffins',
    prepTime: '10 min',
    cookTime: '20 min',
    ingredients: ['360g egg whites', '100g spinach, chopped', '30g low-fat feta cheese', '50g cherry tomatoes, halved'],
    recipe: '1. Preheat oven to 350°F (177°C) and spray a muffin tin with cooking spray.\n2. Mix egg whites, spinach, feta, and tomatoes in a bowl.\n3. Pour into muffin tin and bake for 15–20 min until set.\n4. Serve warm or store for later.',
    macros: { protein: 46, carbs: 10, fats: 4 },
    calories: '275 kcal',
    insights: 'High in vitamins A, C, K, and calcium. Perfect for meal prep.',
    tags: ['high-protein', 'vegetarian', 'low-calorie', 'meal-prep']
  },
  {
    id: '#18',
    name: 'Protein Granola Yogurt Crunch',
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: ['200g 0% fat Greek yogurt', '30g vanilla whey protein powder', '20g homemade protein granola (oats, protein powder, sweetener, baked)', '50g blueberries', '5g flaxseeds'],
    recipe: '1. Mix yogurt with protein powder.\n2. Top with granola, blueberries, and flaxseeds.\n3. Serve immediately for maximum crunch.',
    macros: { protein: 50, carbs: 34, fats: 5 },
    calories: '390 kcal',
    insights: 'High in calcium, vitamin C, and omega-3s. A crunchy, high-protein breakfast.',
    tags: ['high-protein', 'vegetarian', 'quick']
  },
  {
    id: '#19',
    name: 'Chicken Sausage and Veggie Scramble',
    prepTime: '10 min',
    cookTime: '10 min',
    ingredients: ['240g egg whites', '100g lean chicken sausage, cooked', '50g zucchini, diced', '50g bell peppers, diced', '10g nutritional yeast'],
    recipe: '1. Sauté sausage, zucchini, and peppers in a nonstick pan.\n2. Add egg whites and cook until set.\n3. Sprinkle with nutritional yeast and serve warm.',
    macros: { protein: 44, carbs: 12, fats: 8 },
    calories: '320 kcal',
    insights: 'High in vitamins C, A, and B vitamins. A savory, nutrient-dense breakfast.',
    tags: ['high-protein', 'low-carb']
  },
  {
    id: '#20',
    name: 'Mango Coconut Protein Smoothie',
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: ['30g vanilla whey protein powder', '150g frozen mango', '150ml unsweetened coconut milk', '10g shredded coconut', '5g chia seeds'],
    recipe: '1. Blend all ingredients until smooth.\n2. Serve in a chilled glass or bowl, topped with extra coconut if desired.',
    macros: { protein: 27, carbs: 30, fats: 12 },
    calories: '340 kcal',
    insights: 'High in vitamin C, fiber, and healthy fats. A tropical, refreshing breakfast.',
    tags: ['high-protein', 'vegetarian', 'low-calorie']
  },
  {
    id: '#21',
    name: 'Protein Breakfast Pizza',
    prepTime: '10 min',
    cookTime: '15 min',
    ingredients: ['40g oat flour', '30g whey protein powder', '120g egg whites', '50g low-fat pizza sauce', '30g low-fat cheese', '50g spinach'],
    recipe: '1. Blend oat flour, protein powder, and egg whites into a batter.\n2. Cook in a nonstick pan to form a thin crust (3–4 min per side).\n3. Spread sauce, cheese, and spinach on top, then bake at 350°F (177°C) for 5 min.',
    macros: { protein: 53, carbs: 39, fats: 9 },
    calories: '455 kcal',
    insights: 'High in calcium, vitamin K, and protein. A fun, savory breakfast option.',
    tags: ['high-protein', 'vegetarian']
  },
  {
    id: '#22',
    name: 'Almond Butter and Banana Toast',
    prepTime: '5 min',
    cookTime: '2 min',
    ingredients: ['2 slices whole-grain bread', '15g almond butter', '100g banana, sliced', '15g vanilla whey protein powder (mixed with water)'],
    recipe: '1. Toast bread until golden.\n2. Mix protein powder with water to make a drizzle.\n3. Spread almond butter on toast, top with banana slices, and drizzle with protein mixture.',
    macros: { protein: 24, carbs: 55, fats: 10 },
    calories: '400 kcal',
    insights: 'High in potassium, vitamin E, and fiber. A simple, nutrient-rich breakfast.',
    tags: ['high-protein', 'vegetarian', 'quick']
  },
  {
    id: '#23',
    name: 'Protein-Packed Chia Pudding',
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: ['30g vanilla whey protein powder', '20g chia seeds', '150ml unsweetened almond milk', '100g mixed berries', '5g cinnamon'],
    recipe: '1. Mix chia seeds, protein powder, almond milk, and cinnamon in a bowl.\n2. Let sit in the fridge for 4 hours or overnight to thicken.\n3. Top with berries before serving.',
    macros: { protein: 29, carbs: 27, fats: 8 },
    calories: '300 kcal',
    insights: 'High in omega-3s, vitamin C, and fiber. Perfect for meal prep.',
    tags: ['high-protein', 'vegetarian', 'low-calorie', 'meal-prep']
  },
  {
    id: '#24',
    name: 'Savory Cottage Cheese Bowl',
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: ['200g low-fat cottage cheese', '50g cucumber, diced', '50g cherry tomatoes, halved', '10g sunflower seeds', '5g fresh dill'],
    recipe: '1. Mix cottage cheese with cucumber, tomatoes, and dill in a bowl.\n2. Sprinkle with sunflower seeds for crunch.\n3. Serve chilled or at room temperature.',
    macros: { protein: 26, carbs: 14, fats: 9 },
    calories: '240 kcal',
    insights: 'High in calcium, vitamin K, and vitamin E. A light, savory breakfast option.',
    tags: ['high-protein', 'vegetarian', 'low-calorie', 'quick']
  },
  {
    id: '#25',
    name: 'Protein Granola Bars',
    prepTime: '10 min',
    cookTime: '0 min',
    ingredients: ['50g rolled oats', '30g vanilla whey protein powder', '15g almond butter', '10g honey', '10g dried cranberries'],
    recipe: '1. Mix all ingredients in a bowl until a sticky dough forms.\n2. Press into a small baking dish and refrigerate for 2 hours.\n3. Cut into 4 bars and serve or store.',
    macros: { protein: 34, carbs: 65, fats: 12 },
    calories: '490 kcal',
    insights: 'High in fiber, vitamin E, and antioxidants. A convenient, grab-and-go breakfast.',
    tags: ['high-protein', 'vegetarian', 'portable', 'meal-prep']
  }
];